# Generated by Django 3.0.2 on 2020-01-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trubYahooArchive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trubemail',
            name='authorName',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='trubemail',
            name='msgId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trubemail',
            name='msgSnippet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trubemail',
            name='postDate',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='trubemail',
            name='replyTo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='trubemail',
            name='sender',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='trubemail',
            name='subject',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='trubemail',
            name='topicId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trubemail',
            name='userId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trubemail',
            name='rawEmail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
