# Generated by Django 3.0.2 on 2020-01-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trubYahooArchive', '0003_auto_20200102_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trubemail',
            name='sender',
        ),
        migrations.AddField(
            model_name='trubemail',
            name='from_sender',
            field=models.CharField(default='none', max_length=250),
            preserve_default=False,
        ),
    ]
