# Generated by Django 3.0.2 on 2020-01-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trubYahooArchive', '0004_auto_20200102_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trubemail',
            name='from_sender',
            field=models.CharField(max_length=250, verbose_name='from'),
        ),
    ]
