# Generated by Django 3.0.2 on 2020-01-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trubYahooArchive', '0005_auto_20200102_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trubemail',
            name='from_sender',
            field=models.CharField(db_column='from', max_length=250, verbose_name='From'),
        ),
    ]
