# Generated by Django 3.0.2 on 2020-01-02 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trubYahooArchive', '0006_auto_20200102_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trubemail',
            name='from_sender',
        ),
    ]
