# Generated by Django 3.0.2 on 2020-01-02 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trubYahooArchive', '0007_remove_trubemail_from_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trubemail',
            name='replyTo',
        ),
    ]
