# Generated by Django 3.0.2 on 2020-01-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trubYahooArchive', '0008_remove_trubemail_replyto'),
    ]

    operations = [
        migrations.AddField(
            model_name='trubemail',
            name='sender',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
