# Generated by Django 3.0.2 on 2020-01-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trubYahooArchive', '0010_auto_20200103_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trubemail',
            name='msgId',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
